// GENERATED FILE — do not edit by hand.
// Regenerate with: pnpm narrate ch0new
// Source: the **Narration:** blocks of the chapter script.
// Durations are measured from the rendered audio, so they are what the
// chapter's timing is derived from.
import type { BeatNarration } from "../../narration/types";

export const narration = {
  beat0Welcome: {
    key: "beat0Welcome",
    heading: "Beat 0 — Welcome",
    clips: [
      {
        id: "beat0Welcome-000",
        text: "Welcome. Let's learn how AI works.",
        src: "audio/ch0new/beat0Welcome-000.wav",
        durationInFrames: 75,
      },
      {
        id: "beat0Welcome-001",
        text: "It turns out almost every idea inside AI has a mirror in something alive.",
        src: "audio/ch0new/beat0Welcome-001.wav",
        durationInFrames: 136,
      },
      {
        id: "beat0Welcome-002",
        text: "And what really surprised me: some of these algorithms came straight from life — we studied how a living thing did it, then turned it into an algorithm.",
        src: "audio/ch0new/beat0Welcome-002.wav",
        durationInFrames: 265,
      },
      {
        id: "beat0Welcome-003",
        text: "So let's start at the very beginning of life.",
        src: "audio/ch0new/beat0Welcome-003.wav",
        durationInFrames: 76,
      },
      {
        id: "beat0Welcome-004",
        text: "And I mean the very beginning.",
        src: "audio/ch0new/beat0Welcome-004.wav",
        durationInFrames: 49,
      },
    ],
  },
  beatTheVent: {
    key: "beatTheVent",
    heading: "Beat — The Vent",
    clips: [
      {
        id: "beatTheVent-000",
        text: "Let's go back. Not a little back — all the way back.",
        src: "audio/ch0new/beatTheVent-000.wav",
        durationInFrames: 108,
      },
      {
        id: "beatTheVent-001",
        text: "Four and a half billion years, to a planet you would not recognize as home.",
        src: "audio/ch0new/beatTheVent-001.wav",
        durationInFrames: 140,
      },
      {
        id: "beatTheVent-002",
        text: "No oceans. No life.",
        src: "audio/ch0new/beatTheVent-002.wav",
        durationInFrames: 56,
      },
      {
        id: "beatTheVent-003",
        text: "No ground you could stand on without bursting into flame.",
        src: "audio/ch0new/beatTheVent-003.wav",
        durationInFrames: 96,
      },
      {
        id: "beatTheVent-004",
        text: "Just a hot ball of rock, getting hit by other rocks, over and over, for half a billion years.",
        src: "audio/ch0new/beatTheVent-004.wav",
        durationInFrames: 188,
      },
      {
        id: "beatTheVent-005",
        text: "A Moon hanging so close it swallows the sky. A dim sun.",
        src: "audio/ch0new/beatTheVent-005.wav",
        durationInFrames: 121,
      },
      {
        id: "beatTheVent-006",
        text: "Air that would kill you in a breath.",
        src: "audio/ch0new/beatTheVent-006.wav",
        durationInFrames: 54,
      },
      {
        id: "beatTheVent-007",
        text: "And then — slowly — it cools. The rock hardens.",
        src: "audio/ch0new/beatTheVent-007.wav",
        durationInFrames: 107,
      },
      {
        id: "beatTheVent-008",
        text: "The steam in the air falls back down as rain, and keeps falling, for thousands of years, until it pools in the low places and becomes the first oceans.",
        src: "audio/ch0new/beatTheVent-008.wav",
        durationInFrames: 276,
      },
      {
        id: "beatTheVent-009",
        text: "The sky stays a hazy pink, full of methane, the dim Sun glowing through it.",
        src: "audio/ch0new/beatTheVent-009.wav",
        durationInFrames: 147,
      },
      {
        id: "beatTheVent-010",
        text: "Geologists have a name for this stretch of time.",
        src: "audio/ch0new/beatTheVent-010.wav",
        durationInFrames: 86,
      },
      {
        id: "beatTheVent-011",
        text: "They call it the Archean. Nothing alive yet.",
        src: "audio/ch0new/beatTheVent-011.wav",
        durationInFrames: 87,
      },
      {
        id: "beatTheVent-012",
        text: "But the stage is set.",
        src: "audio/ch0new/beatTheVent-012.wav",
        durationInFrames: 38,
      },
      {
        id: "beatTheVent-013",
        text: "Now — go deeper.",
        src: "audio/ch0new/beatTheVent-013.wav",
        durationInFrames: 42,
      },
      {
        id: "beatTheVent-014",
        text: "Past the surface, past the light, all the way down to the bottom of that new ocean, where the sun doesn't reach and never has.",
        src: "audio/ch0new/beatTheVent-014.wav",
        durationInFrames: 225,
      },
      {
        id: "beatTheVent-015",
        text: "Down here, there's a crack in the seafloor.",
        src: "audio/ch0new/beatTheVent-015.wav",
        durationInFrames: 78,
      },
      {
        id: "beatTheVent-016",
        text: "Hot, mineral-heavy water is forcing its way up out of it, into the cold dark above — the planet's own heat, still leaking out from underneath. No sunlight.",
        src: "audio/ch0new/beatTheVent-016.wav",
        durationInFrames: 298,
      },
      {
        id: "beatTheVent-017",
        text: "No warmth from above.",
        src: "audio/ch0new/beatTheVent-017.wav",
        durationInFrames: 41,
      },
      {
        id: "beatTheVent-018",
        text: "Just this: a narrow column of hot, chemical-rich water, pouring out of the rock, forever.",
        src: "audio/ch0new/beatTheVent-018.wav",
        durationInFrames: 187,
      },
      {
        id: "beatTheVent-019",
        text: "And right where that water hits the rock — something is alive.",
        src: "audio/ch0new/beatTheVent-019.wav",
        durationInFrames: 103,
      },
      {
        id: "beatTheVent-020",
        text: "Not swimming nearby. Not approaching. Stuck there.",
        src: "audio/ch0new/beatTheVent-020.wav",
        durationInFrames: 107,
      },
      {
        id: "beatTheVent-021",
        text: "Fixed in place, the way a barnacle clings to a piling, except there's no barnacle yet, no shell, no name for what this even is.",
        src: "audio/ch0new/beatTheVent-021.wav",
        durationInFrames: 259,
      },
      {
        id: "beatTheVent-022",
        text: "Just a smear of something, anchored exactly where the vent water arrives.",
        src: "audio/ch0new/beatTheVent-022.wav",
        durationInFrames: 133,
      },
      {
        id: "beatTheVent-023",
        text: "This is the first thing alive on this planet.",
        src: "audio/ch0new/beatTheVent-023.wav",
        durationInFrames: 73,
      },
      {
        id: "beatTheVent-024",
        text: "And it has no way to move.",
        src: "audio/ch0new/beatTheVent-024.wav",
        durationInFrames: 46,
      },
      {
        id: "beatTheVent-025",
        text: "It doesn't need one — there's nowhere to go and nothing to chase.",
        src: "audio/ch0new/beatTheVent-025.wav",
        durationInFrames: 114,
      },
      {
        id: "beatTheVent-026",
        text: "Everything it needs is already arriving, for free, forever, as long as it stays exactly where it is.",
        src: "audio/ch0new/beatTheVent-026.wav",
        durationInFrames: 199,
      },
      {
        id: "beatTheVent-027",
        text: "Let's find out what \"alive\" even means, for something that never goes anywhere.",
        src: "audio/ch0new/beatTheVent-027.wav",
        durationInFrames: 141,
      },
    ],
  },
  beatTheReaction: {
    key: "beatTheReaction",
    heading: "Beat — The Reaction",
    clips: [
      {
        id: "beatTheReaction-000",
        text: "So what does \"alive\" look like, when you can't move and there's nothing to decide?",
        src: "audio/ch0new/beatTheReaction-000.wav",
        durationInFrames: 135,
      },
      {
        id: "beatTheReaction-001",
        text: "It looks like this: chemistry hits a surface, and the surface uses it.",
        src: "audio/ch0new/beatTheReaction-001.wav",
        durationInFrames: 139,
      },
      {
        id: "beatTheReaction-002",
        text: "That vent water isn't just warm — it's carrying two things this thing has learned to grab onto. Hydrogen.",
        src: "audio/ch0new/beatTheReaction-002.wav",
        durationInFrames: 192,
      },
      {
        id: "beatTheReaction-003",
        text: "And hydrogen sulfide — the same rotten-egg smell you'd get from a match, if there were any air down here to carry it.",
        src: "audio/ch0new/beatTheReaction-003.wav",
        durationInFrames: 209,
      },
      {
        id: "beatTheReaction-004",
        text: "Both keep pouring out of the crack, endlessly, straight from the rock itself.",
        src: "audio/ch0new/beatTheReaction-004.wav",
        durationInFrames: 143,
      },
      {
        id: "beatTheReaction-005",
        text: "And when either one touches this thing's outer surface, something happens. Not a decision.",
        src: "audio/ch0new/beatTheReaction-005.wav",
        durationInFrames: 167,
      },
      {
        id: "beatTheReaction-006",
        text: "Not a signal traveling anywhere, because there's nowhere in here for a signal to travel to.",
        src: "audio/ch0new/beatTheReaction-006.wav",
        durationInFrames: 164,
      },
      {
        id: "beatTheReaction-007",
        text: "Just a reaction — the same one, over and over, everywhere the chemistry touches.",
        src: "audio/ch0new/beatTheReaction-007.wav",
        durationInFrames: 167,
      },
      {
        id: "beatTheReaction-008",
        text: "A little bit of energy gets pulled out.",
        src: "audio/ch0new/beatTheReaction-008.wav",
        durationInFrames: 65,
      },
      {
        id: "beatTheReaction-009",
        text: "A little bit of carbon, drifting nearby in the water, gets grabbed and stitched into the body.",
        src: "audio/ch0new/beatTheReaction-009.wav",
        durationInFrames: 164,
      },
      {
        id: "beatTheReaction-010",
        text: "That's the whole event. No searching. No aiming.",
        src: "audio/ch0new/beatTheReaction-010.wav",
        durationInFrames: 96,
      },
      {
        id: "beatTheReaction-011",
        text: "No moment where anything is figured out.",
        src: "audio/ch0new/beatTheReaction-011.wav",
        durationInFrames: 71,
      },
      {
        id: "beatTheReaction-012",
        text: "The chemistry arrives, the surface reacts, and the thing gets very slightly more of itself.",
        src: "audio/ch0new/beatTheReaction-012.wav",
        durationInFrames: 176,
      },
      {
        id: "beatTheReaction-013",
        text: "Do that enough times, for long enough, and you don't get a decision.",
        src: "audio/ch0new/beatTheReaction-013.wav",
        durationInFrames: 130,
      },
      {
        id: "beatTheReaction-014",
        text: "You get something better suited to this question than a decision ever could be: you just get more of it.",
        src: "audio/ch0new/beatTheReaction-014.wav",
        durationInFrames: 171,
      },
    ],
  },
  beatSplitting: {
    key: "beatSplitting",
    heading: "Beat — Splitting",
    clips: [
      {
        id: "beatSplitting-000",
        text: "It stays like this for a long time.",
        src: "audio/ch0new/beatSplitting-000.wav",
        durationInFrames: 66,
      },
      {
        id: "beatSplitting-001",
        text: "Not one reaction — millions of them, every second, all over the same tiny patch of rock.",
        src: "audio/ch0new/beatSplitting-001.wav",
        durationInFrames: 179,
      },
      {
        id: "beatSplitting-002",
        text: "Hydrogen arrives, gets used.",
        src: "audio/ch0new/beatSplitting-002.wav",
        durationInFrames: 73,
      },
      {
        id: "beatSplitting-003",
        text: "Sulfide arrives, gets used.",
        src: "audio/ch0new/beatSplitting-003.wav",
        durationInFrames: 72,
      },
      {
        id: "beatSplitting-004",
        text: "Carbon gets stitched in, one atom at a time, until there's enough of this thing to do something it couldn't do before.",
        src: "audio/ch0new/beatSplitting-004.wav",
        durationInFrames: 204,
      },
      {
        id: "beatSplitting-005",
        text: "It splits.",
        src: "audio/ch0new/beatSplitting-005.wav",
        durationInFrames: 25,
      },
      {
        id: "beatSplitting-006",
        text: "Not on purpose — there's no purpose here yet, remember.",
        src: "audio/ch0new/beatSplitting-006.wav",
        durationInFrames: 113,
      },
      {
        id: "beatSplitting-007",
        text: "It just gets big enough that being two things is more stable than being one, and it comes apart into two smears instead of one.",
        src: "audio/ch0new/beatSplitting-007.wav",
        durationInFrames: 222,
      },
      {
        id: "beatSplitting-008",
        text: "Both stuck to the rock.",
        src: "audio/ch0new/beatSplitting-008.wav",
        durationInFrames: 38,
      },
      {
        id: "beatSplitting-009",
        text: "Both sitting in the same stream of chemistry.",
        src: "audio/ch0new/beatSplitting-009.wav",
        durationInFrames: 74,
      },
      {
        id: "beatSplitting-010",
        text: "Both doing the exact same thing the first one did, because there was never anything else to do.",
        src: "audio/ch0new/beatSplitting-010.wav",
        durationInFrames: 167,
      },
      {
        id: "beatSplitting-011",
        text: "Then those two become four. Four become eight.",
        src: "audio/ch0new/beatSplitting-011.wav",
        durationInFrames: 87,
      },
      {
        id: "beatSplitting-012",
        text: "Not spreading out to look for anything new — just filling in more of the same rock, wherever the vent water reaches.",
        src: "audio/ch0new/beatSplitting-012.wav",
        durationInFrames: 204,
      },
      {
        id: "beatSplitting-013",
        text: "A crust of living matter, growing outward from the crack, one identical reaction repeating itself across a thousand points at once.",
        src: "audio/ch0new/beatSplitting-013.wav",
        durationInFrames: 247,
      },
      {
        id: "beatSplitting-014",
        text: "And here's the part worth sitting with: nothing about this required intelligence.",
        src: "audio/ch0new/beatSplitting-014.wav",
        durationInFrames: 140,
      },
      {
        id: "beatSplitting-015",
        text: "Not a flicker of it.",
        src: "audio/ch0new/beatSplitting-015.wav",
        durationInFrames: 36,
      },
      {
        id: "beatSplitting-016",
        text: "You don't need to sense anything, weigh anything, or choose anything to do what this is doing.",
        src: "audio/ch0new/beatSplitting-016.wav",
        durationInFrames: 166,
      },
      {
        id: "beatSplitting-017",
        text: "You just need to be shaped in a way that a molecule happens to fit into — and then let chemistry do the rest, over and over, for as long as the vent keeps flowing.",
        src: "audio/ch0new/beatSplitting-017.wav",
        durationInFrames: 295,
      },
      {
        id: "beatSplitting-018",
        text: "This is as alive as anything gets to be, for a very long time.",
        src: "audio/ch0new/beatSplitting-018.wav",
        durationInFrames: 121,
      },
      {
        id: "beatSplitting-019",
        text: "A reaction, repeating itself, spreading across a rock, in the dark, at the bottom of an ocean nobody would ever see.",
        src: "audio/ch0new/beatSplitting-019.wav",
        durationInFrames: 231,
      },
      {
        id: "beatSplitting-020",
        text: "And it works. It works for a very, very long time.",
        src: "audio/ch0new/beatSplitting-020.wav",
        durationInFrames: 111,
      },
      {
        id: "beatSplitting-021",
        text: "But it isn't the only thing that will ever work.",
        src: "audio/ch0new/beatSplitting-021.wav",
        durationInFrames: 73,
      },
    ],
  },
} as const satisfies Record<string, BeatNarration>;

export type CH0NEWBeatKey = keyof typeof narration;
