// GENERATED FILE — do not edit by hand.
// Regenerate with: pnpm narrate ch0
// Source: the **Narration:** blocks of the chapter script.
// Durations are measured from the rendered audio, so they are what the
// chapter's timing is derived from.
import type { BeatNarration } from "../../narration/types";

export const narration = {
  beat0Welcome: {
    key: "beat0Welcome",
    heading: "Beat 0 — Welcome",
    clips: [
      {
        id: "beat0Welcome-000",
        text: "Welcome. Let's learn how AI works.",
        src: "audio/ch0/beat0Welcome-000.wav",
        durationInFrames: 75,
      },
      {
        id: "beat0Welcome-001",
        text: "It turns out almost every idea inside AI has a mirror in something alive.",
        src: "audio/ch0/beat0Welcome-001.wav",
        durationInFrames: 136,
      },
      {
        id: "beat0Welcome-002",
        text: "And what really surprised me: some of these algorithms came straight from life — we studied how a living thing did it, then turned it into an algorithm.",
        src: "audio/ch0/beat0Welcome-002.wav",
        durationInFrames: 265,
      },
      {
        id: "beat0Welcome-003",
        text: "So let's start at the very beginning of life.",
        src: "audio/ch0/beat0Welcome-003.wav",
        durationInFrames: 76,
      },
      {
        id: "beat0Welcome-004",
        text: "And I mean the very beginning.",
        src: "audio/ch0/beat0Welcome-004.wav",
        durationInFrames: 49,
      },
    ],
  },
  beat1YoungEarth: {
    key: "beat1YoungEarth",
    heading: "Beat 1 — The Young Earth",
    clips: [
      {
        id: "beat1YoungEarth-000",
        text: "Let's go back. Not a little back — all the way back.",
        src: "audio/ch0/beat1YoungEarth-000.wav",
        durationInFrames: 108,
      },
      {
        id: "beat1YoungEarth-001",
        text: "Four and a half billion years, to a planet you would not recognize as home.",
        src: "audio/ch0/beat1YoungEarth-001.wav",
        durationInFrames: 140,
      },
      {
        id: "beat1YoungEarth-002",
        text: "No oceans. No life.",
        src: "audio/ch0/beat1YoungEarth-002.wav",
        durationInFrames: 56,
      },
      {
        id: "beat1YoungEarth-003",
        text: "No ground you could stand on without bursting into flame.",
        src: "audio/ch0/beat1YoungEarth-003.wav",
        durationInFrames: 96,
      },
      {
        id: "beat1YoungEarth-004",
        text: "Just a hot ball of rock, getting hit by other rocks, over and over, for half a billion years.",
        src: "audio/ch0/beat1YoungEarth-004.wav",
        durationInFrames: 188,
      },
      {
        id: "beat1YoungEarth-005",
        text: "A Moon hanging so close it swallows the sky. A dim sun.",
        src: "audio/ch0/beat1YoungEarth-005.wav",
        durationInFrames: 121,
      },
      {
        id: "beat1YoungEarth-006",
        text: "Air that would kill you in a breath.",
        src: "audio/ch0/beat1YoungEarth-006.wav",
        durationInFrames: 54,
      },
      {
        id: "beat1YoungEarth-007",
        text: "And then — slowly — it cools. The rock hardens.",
        src: "audio/ch0/beat1YoungEarth-007.wav",
        durationInFrames: 107,
      },
      {
        id: "beat1YoungEarth-008",
        text: "The steam in the air falls back down as rain, and keeps falling, for thousands of years, until it pools in the low places and becomes the first oceans.",
        src: "audio/ch0/beat1YoungEarth-008.wav",
        durationInFrames: 276,
      },
      {
        id: "beat1YoungEarth-009",
        text: "The sky stays a hazy pink, full of methane, the dim Sun glowing through it.",
        src: "audio/ch0/beat1YoungEarth-009.wav",
        durationInFrames: 147,
      },
      {
        id: "beat1YoungEarth-010",
        text: "Geologists have a name for this stretch of time.",
        src: "audio/ch0/beat1YoungEarth-010.wav",
        durationInFrames: 86,
      },
      {
        id: "beat1YoungEarth-011",
        text: "They call it the Archean. Nothing alive yet.",
        src: "audio/ch0/beat1YoungEarth-011.wav",
        durationInFrames: 87,
      },
      {
        id: "beat1YoungEarth-012",
        text: "But the stage is set.",
        src: "audio/ch0/beat1YoungEarth-012.wav",
        durationInFrames: 38,
      },
      {
        id: "beat1YoungEarth-013",
        text: "And in those warm, shallow seas — something happens.",
        src: "audio/ch0/beat1YoungEarth-013.wav",
        durationInFrames: 112,
      },
    ],
  },
  beat2FirstOceans: {
    key: "beat2FirstOceans",
    heading: "Beat 2 — The First Oceans",
    clips: [
      {
        id: "beat2FirstOceans-000",
        text: "Here's the thing about this ocean: it's empty.",
        src: "audio/ch0/beat2FirstOceans-000.wav",
        durationInFrames: 83,
      },
      {
        id: "beat2FirstOceans-001",
        text: "No fish. No plants.",
        src: "audio/ch0/beat2FirstOceans-001.wav",
        durationInFrames: 55,
      },
      {
        id: "beat2FirstOceans-002",
        text: "No coral, no crabs, nothing with a face.",
        src: "audio/ch0/beat2FirstOceans-002.wav",
        durationInFrames: 99,
      },
      {
        id: "beat2FirstOceans-003",
        text: "Just water, and sunlight, and a slow film of slime on the seabed.",
        src: "audio/ch0/beat2FirstOceans-003.wav",
        durationInFrames: 130,
      },
      {
        id: "beat2FirstOceans-004",
        text: "If you went for a swim, you'd be the most complicated thing for a billion years in any direction.",
        src: "audio/ch0/beat2FirstOceans-004.wav",
        durationInFrames: 167,
      },
      {
        id: "beat2FirstOceans-005",
        text: "But it isn't quite empty.",
        src: "audio/ch0/beat2FirstOceans-005.wav",
        durationInFrames: 44,
      },
      {
        id: "beat2FirstOceans-006",
        text: "There's something in the water.",
        src: "audio/ch0/beat2FirstOceans-006.wav",
        durationInFrames: 42,
      },
      {
        id: "beat2FirstOceans-007",
        text: "Something so small you'd need a microscope to find it.",
        src: "audio/ch0/beat2FirstOceans-007.wav",
        durationInFrames: 100,
      },
      {
        id: "beat2FirstOceans-008",
        text: "So simple you wouldn't call it intelligent.",
        src: "audio/ch0/beat2FirstOceans-008.wav",
        durationInFrames: 76,
      },
      {
        id: "beat2FirstOceans-009",
        text: "So basic you might not even call it alive.",
        src: "audio/ch0/beat2FirstOceans-009.wav",
        durationInFrames: 82,
      },
      {
        id: "beat2FirstOceans-010",
        text: "But it is. Just barely.",
        src: "audio/ch0/beat2FirstOceans-010.wav",
        durationInFrames: 53,
      },
      {
        id: "beat2FirstOceans-011",
        text: "In the most stripped-down way anything has ever managed to be alive.",
        src: "audio/ch0/beat2FirstOceans-011.wav",
        durationInFrames: 111,
      },
    ],
  },
  beat3MeetTheCell: {
    key: "beat3MeetTheCell",
    heading: "Beat 3 — Meet the Cell",
    clips: [
      {
        id: "beat3MeetTheCell-000",
        text: "So — meet the hero of our story.",
        src: "audio/ch0/beat3MeetTheCell-000.wav",
        durationInFrames: 67,
      },
      {
        id: "beat3MeetTheCell-001",
        text: "And honestly, it's not much to look at. It's a blob.",
        src: "audio/ch0/beat3MeetTheCell-001.wav",
        durationInFrames: 108,
      },
      {
        id: "beat3MeetTheCell-002",
        text: "A few specks of goo, a couple micrometers long, with some threads stuck on the outside. No eyes.",
        src: "audio/ch0/beat3MeetTheCell-002.wav",
        durationInFrames: 198,
      },
      {
        id: "beat3MeetTheCell-003",
        text: "No brain — brains haven't been invented yet, anywhere on the planet. No plan.",
        src: "audio/ch0/beat3MeetTheCell-003.wav",
        durationInFrames: 161,
      },
      {
        id: "beat3MeetTheCell-004",
        text: "If you met it, you wouldn't even be sure it was alive.",
        src: "audio/ch0/beat3MeetTheCell-004.wav",
        durationInFrames: 92,
      },
      {
        id: "beat3MeetTheCell-005",
        text: "Those threads are the one good trick.",
        src: "audio/ch0/beat3MeetTheCell-005.wav",
        durationInFrames: 54,
      },
      {
        id: "beat3MeetTheCell-006",
        text: "They're called flagella, and the cell can spin them like tiny propellers to shove itself through the water. That's it.",
        src: "audio/ch0/beat3MeetTheCell-006.wav",
        durationInFrames: 192,
      },
      {
        id: "beat3MeetTheCell-007",
        text: "That's the whole toolkit.",
        src: "audio/ch0/beat3MeetTheCell-007.wav",
        durationInFrames: 40,
      },
      {
        id: "beat3MeetTheCell-008",
        text: "And it has exactly one job — the same job as every living thing that comes after it, including you: don't die.",
        src: "audio/ch0/beat3MeetTheCell-008.wav",
        durationInFrames: 213,
      },
      {
        id: "beat3MeetTheCell-009",
        text: "That's the entire story for the next three billion years. One cell. One job.",
        src: "audio/ch0/beat3MeetTheCell-009.wav",
        durationInFrames: 154,
      },
      {
        id: "beat3MeetTheCell-010",
        text: "It doesn't know it has the job. Nobody told it.",
        src: "audio/ch0/beat3MeetTheCell-010.wav",
        durationInFrames: 89,
      },
      {
        id: "beat3MeetTheCell-011",
        text: "It just has it.",
        src: "audio/ch0/beat3MeetTheCell-011.wav",
        durationInFrames: 29,
      },
    ],
  },
  beat4FindingFood: {
    key: "beat4FindingFood",
    heading: "Beat 4 — Finding Food",
    clips: [
      {
        id: "beat4FindingFood-000",
        text: "Job number one: find food.",
        src: "audio/ch0/beat4FindingFood-000.wav",
        durationInFrames: 66,
      },
      {
        id: "beat4FindingFood-001",
        text: "Though find is a generous word.",
        src: "audio/ch0/beat4FindingFood-001.wav",
        durationInFrames: 53,
      },
      {
        id: "beat4FindingFood-002",
        text: "Remember — no eyes.",
        src: "audio/ch0/beat4FindingFood-002.wav",
        durationInFrames: 45,
      },
      {
        id: "beat4FindingFood-003",
        text: "The cell has no idea where anything is.",
        src: "audio/ch0/beat4FindingFood-003.wav",
        durationInFrames: 71,
      },
      {
        id: "beat4FindingFood-004",
        text: "It can't look around. It can't aim.",
        src: "audio/ch0/beat4FindingFood-004.wav",
        durationInFrames: 71,
      },
      {
        id: "beat4FindingFood-005",
        text: "So how does a blob with no senses track down lunch?",
        src: "audio/ch0/beat4FindingFood-005.wav",
        durationInFrames: 101,
      },
      {
        id: "beat4FindingFood-006",
        text: "It cheats. Sort of.",
        src: "audio/ch0/beat4FindingFood-006.wav",
        durationInFrames: 51,
      },
      {
        id: "beat4FindingFood-007",
        text: "Scattered across its surface are tiny chemical sensors — little protein gates that twitch when the right molecule drifts past.",
        src: "audio/ch0/beat4FindingFood-007.wav",
        durationInFrames: 226,
      },
      {
        id: "beat4FindingFood-008",
        text: "A bit of sugar bumps one, the gate shifts, and a signal runs inward to the propellers.",
        src: "audio/ch0/beat4FindingFood-008.wav",
        durationInFrames: 161,
      },
      {
        id: "beat4FindingFood-009",
        text: "But how do those propellers actually move the cell?",
        src: "audio/ch0/beat4FindingFood-009.wav",
        durationInFrames: 89,
      },
      {
        id: "beat4FindingFood-010",
        text: "Here's the part I love.",
        src: "audio/ch0/beat4FindingFood-010.wav",
        durationInFrames: 41,
      },
      {
        id: "beat4FindingFood-011",
        text: "Each whip is spun by its own tiny motor, sunk into the cell wall — a real, turning motor, one of the only ones nature ever built.",
        src: "audio/ch0/beat4FindingFood-011.wav",
        durationInFrames: 254,
      },
      {
        id: "beat4FindingFood-012",
        text: "And it runs both ways.",
        src: "audio/ch0/beat4FindingFood-012.wav",
        durationInFrames: 44,
      },
      {
        id: "beat4FindingFood-013",
        text: "Spin the whips one direction, and they wind together into a single bundle that drives the cell smoothly forward.",
        src: "audio/ch0/beat4FindingFood-013.wav",
        durationInFrames: 189,
      },
      {
        id: "beat4FindingFood-014",
        text: "Spin them the other way, and the bundle bursts apart — each whip thrashing on its own — and the cell just spins in place, pointing nowhere.",
        src: "audio/ch0/beat4FindingFood-014.wav",
        durationInFrames: 254,
      },
      {
        id: "beat4FindingFood-015",
        text: "So which way do the motors turn?",
        src: "audio/ch0/beat4FindingFood-015.wav",
        durationInFrames: 61,
      },
      {
        id: "beat4FindingFood-016",
        text: "That's the dead-simple part.",
        src: "audio/ch0/beat4FindingFood-016.wav",
        durationInFrames: 47,
      },
      {
        id: "beat4FindingFood-017",
        text: "When the sugar is getting stronger — they bundle, and the cell glides forward.",
        src: "audio/ch0/beat4FindingFood-017.wav",
        durationInFrames: 137,
      },
      {
        id: "beat4FindingFood-018",
        text: "When it's getting weaker — they scatter, and the cell spins, until it's aimed somewhere new.",
        src: "audio/ch0/beat4FindingFood-018.wav",
        durationInFrames: 163,
      },
      {
        id: "beat4FindingFood-019",
        text: "Then it sets off again.",
        src: "audio/ch0/beat4FindingFood-019.wav",
        durationInFrames: 43,
      },
      {
        id: "beat4FindingFood-020",
        text: "Forward. Spin. Forward. Spin.",
        src: "audio/ch0/beat4FindingFood-020.wav",
        durationInFrames: 94,
      },
      {
        id: "beat4FindingFood-021",
        text: "And somehow — over thousands of these — it ends up at the food. Not gracefully. Not on purpose. Just, eventually.",
        src: "audio/ch0/beat4FindingFood-021.wav",
        durationInFrames: 245,
      },
      {
        id: "beat4FindingFood-022",
        text: "The way water finds its way downhill.",
        src: "audio/ch0/beat4FindingFood-022.wav",
        durationInFrames: 65,
      },
    ],
  },
  beat5AvoidingDanger: {
    key: "beat5AvoidingDanger",
    heading: "Beat 5 — Avoiding Danger",
    clips: [
      {
        id: "beat5AvoidingDanger-000",
        text: "Job number two: don't get poisoned.",
        src: "audio/ch0/beat5AvoidingDanger-000.wav",
        durationInFrames: 72,
      },
      {
        id: "beat5AvoidingDanger-001",
        text: "Different molecule this time.",
        src: "audio/ch0/beat5AvoidingDanger-001.wav",
        durationInFrames: 53,
      },
      {
        id: "beat5AvoidingDanger-002",
        text: "Not food — a toxin.",
        src: "audio/ch0/beat5AvoidingDanger-002.wav",
        durationInFrames: 51,
      },
      {
        id: "beat5AvoidingDanger-003",
        text: "Something drifting through the water that the cell really, really does not want to swim into.",
        src: "audio/ch0/beat5AvoidingDanger-003.wav",
        durationInFrames: 151,
      },
      {
        id: "beat5AvoidingDanger-004",
        text: "It's got a sensor for that too.",
        src: "audio/ch0/beat5AvoidingDanger-004.wav",
        durationInFrames: 55,
      },
      {
        id: "beat5AvoidingDanger-005",
        text: "A different gate, tuned to a different molecule.",
        src: "audio/ch0/beat5AvoidingDanger-005.wav",
        durationInFrames: 90,
      },
      {
        id: "beat5AvoidingDanger-006",
        text: "The toxin bumps it, a signal runs inward, the propellers respond — same machinery as before.",
        src: "audio/ch0/beat5AvoidingDanger-006.wav",
        durationInFrames: 191,
      },
      {
        id: "beat5AvoidingDanger-007",
        text: "But watch closely, because this time the behavior looks backwards.",
        src: "audio/ch0/beat5AvoidingDanger-007.wav",
        durationInFrames: 125,
      },
      {
        id: "beat5AvoidingDanger-008",
        text: "Toxin getting stronger — the propellers scatter, and the cell spins in place. Chaos. No commitment.",
        src: "audio/ch0/beat5AvoidingDanger-008.wav",
        durationInFrames: 205,
      },
      {
        id: "beat5AvoidingDanger-009",
        text: "Toxin getting weaker — the threat falling away behind it — the propellers bundle, and the cell swims, hard, in a straight line. Out.",
        src: "audio/ch0/beat5AvoidingDanger-009.wav",
        durationInFrames: 263,
      },
      {
        id: "beat5AvoidingDanger-010",
        text: "Spin. Forward. Spin. Forward.",
        src: "audio/ch0/beat5AvoidingDanger-010.wav",
        durationInFrames: 94,
      },
      {
        id: "beat5AvoidingDanger-011",
        text: "Totally different strategy. Totally different problem.",
        src: "audio/ch0/beat5AvoidingDanger-011.wav",
        durationInFrames: 105,
      },
      {
        id: "beat5AvoidingDanger-012",
        text: "Or so it looks.",
        src: "audio/ch0/beat5AvoidingDanger-012.wav",
        durationInFrames: 35,
      },
    ],
  },
  beat6SameTwoMoves: {
    key: "beat6SameTwoMoves",
    heading: "Beat 6 — Same Two Moves",
    clips: [
      {
        id: "beat6SameTwoMoves-000",
        text: "Now forget the sugar. Forget the toxin.",
        src: "audio/ch0/beat6SameTwoMoves-000.wav",
        durationInFrames: 81,
      },
      {
        id: "beat6SameTwoMoves-001",
        text: "Stop watching what the cell is chasing or running from — and just watch what its body is actually doing.",
        src: "audio/ch0/beat6SameTwoMoves-001.wav",
        durationInFrames: 183,
      },
      {
        id: "beat6SameTwoMoves-002",
        text: "Food story: forward, forward, forward — then pause, spin, point somewhere new — then forward again.",
        src: "audio/ch0/beat6SameTwoMoves-002.wav",
        durationInFrames: 239,
      },
      {
        id: "beat6SameTwoMoves-003",
        text: "Danger story: pause, spin, point somewhere new — then, once the danger's behind it, forward, forward, forward.",
        src: "audio/ch0/beat6SameTwoMoves-003.wav",
        durationInFrames: 267,
      },
      {
        id: "beat6SameTwoMoves-004",
        text: "See it yet?",
        src: "audio/ch0/beat6SameTwoMoves-004.wav",
        durationInFrames: 28,
      },
      {
        id: "beat6SameTwoMoves-005",
        text: "There. That's the thing — and honestly, it still gets me every time.",
        src: "audio/ch0/beat6SameTwoMoves-005.wav",
        durationInFrames: 135,
      },
      {
        id: "beat6SameTwoMoves-006",
        text: "Two completely different problems, food and poison, opposites — and underneath, the cell is doing the exact same two moves.",
        src: "audio/ch0/beat6SameTwoMoves-006.wav",
        durationInFrames: 242,
      },
      {
        id: "beat6SameTwoMoves-007",
        text: "The identical dance, both times.",
        src: "audio/ch0/beat6SameTwoMoves-007.wav",
        durationInFrames: 79,
      },
      {
        id: "beat6SameTwoMoves-008",
        text: "Swim. Spin. That's the whole vocabulary.",
        src: "audio/ch0/beat6SameTwoMoves-008.wav",
        durationInFrames: 96,
      },
      {
        id: "beat6SameTwoMoves-009",
        text: "And here's the part to hang onto: it's never both at once.",
        src: "audio/ch0/beat6SameTwoMoves-009.wav",
        durationInFrames: 106,
      },
      {
        id: "beat6SameTwoMoves-010",
        text: "At any instant, the cell is doing exactly one of them.",
        src: "audio/ch0/beat6SameTwoMoves-010.wav",
        durationInFrames: 104,
      },
      {
        id: "beat6SameTwoMoves-011",
        text: "Those threads can gather into a single bundle and push — or fly apart and stir the water — but not both.",
        src: "audio/ch0/beat6SameTwoMoves-011.wav",
        durationInFrames: 191,
      },
      {
        id: "beat6SameTwoMoves-012",
        text: "There's no half-swim, no swim-and-spin.",
        src: "audio/ch0/beat6SameTwoMoves-012.wav",
        durationInFrames: 77,
      },
      {
        id: "beat6SameTwoMoves-013",
        text: "One, or the other. Always.",
        src: "audio/ch0/beat6SameTwoMoves-013.wav",
        durationInFrames: 66,
      },
      {
        id: "beat6SameTwoMoves-014",
        text: "Two moves, for every problem this thing will face in three billion years.",
        src: "audio/ch0/beat6SameTwoMoves-014.wav",
        durationInFrames: 128,
      },
      {
        id: "beat6SameTwoMoves-015",
        text: "Biologists gave them names.",
        src: "audio/ch0/beat6SameTwoMoves-015.wav",
        durationInFrames: 59,
      },
      {
        id: "beat6SameTwoMoves-016",
        text: "The swim, they call a run. The spin, they call a tumble. Put them together — run and tumble. The oldest dance on Earth.",
        src: "audio/ch0/beat6SameTwoMoves-016.wav",
        durationInFrames: 241,
      },
    ],
  },
  beat7SimpleRule: {
    key: "beat7SimpleRule",
    heading: "Beat 7 — The Simple Rule",
    clips: [
      {
        id: "beat7SimpleRule-000",
        text: "Let's say what the cell is doing out loud. Not in chemistry. Not in molecules. Just plain words.",
        src: "audio/ch0/beat7SimpleRule-000.wav",
        durationInFrames: 199,
      },
      {
        id: "beat7SimpleRule-001",
        text: "When the world gets better — keep going.",
        src: "audio/ch0/beat7SimpleRule-001.wav",
        durationInFrames: 72,
      },
      {
        id: "beat7SimpleRule-002",
        text: "When the world gets worse — change direction.",
        src: "audio/ch0/beat7SimpleRule-002.wav",
        durationInFrames: 82,
      },
      {
        id: "beat7SimpleRule-003",
        text: "That's it. That's the whole animal.",
        src: "audio/ch0/beat7SimpleRule-003.wav",
        durationInFrames: 60,
      },
      {
        id: "beat7SimpleRule-004",
        text: "That's how it finds food.",
        src: "audio/ch0/beat7SimpleRule-004.wav",
        durationInFrames: 45,
      },
      {
        id: "beat7SimpleRule-005",
        text: "That's how it dodges poison.",
        src: "audio/ch0/beat7SimpleRule-005.wav",
        durationInFrames: 51,
      },
      {
        id: "beat7SimpleRule-006",
        text: "That's how it's stayed alive in this ocean since before the ocean had a name.",
        src: "audio/ch0/beat7SimpleRule-006.wav",
        durationInFrames: 124,
      },
      {
        id: "beat7SimpleRule-007",
        text: "For food, better means getting closer.",
        src: "audio/ch0/beat7SimpleRule-007.wav",
        durationInFrames: 75,
      },
      {
        id: "beat7SimpleRule-008",
        text: "For danger, better means getting farther.",
        src: "audio/ch0/beat7SimpleRule-008.wav",
        durationInFrames: 75,
      },
      {
        id: "beat7SimpleRule-009",
        text: "The cell never has to know which is which.",
        src: "audio/ch0/beat7SimpleRule-009.wav",
        durationInFrames: 68,
      },
      {
        id: "beat7SimpleRule-010",
        text: "It only ever has to know one thing: are things getting better, or not?",
        src: "audio/ch0/beat7SimpleRule-010.wav",
        durationInFrames: 131,
      },
      {
        id: "beat7SimpleRule-011",
        text: "Sit with that for a second.",
        src: "audio/ch0/beat7SimpleRule-011.wav",
        durationInFrames: 47,
      },
      {
        id: "beat7SimpleRule-012",
        text: "Two behaviors that look like total opposites — seeking and fleeing — turn out to be the same move in a different costume.",
        src: "audio/ch0/beat7SimpleRule-012.wav",
        durationInFrames: 220,
      },
      {
        id: "beat7SimpleRule-013",
        text: "The cell didn't need a program for food and a separate program for danger.",
        src: "audio/ch0/beat7SimpleRule-013.wav",
        durationInFrames: 123,
      },
      {
        id: "beat7SimpleRule-014",
        text: "It needed one rule.",
        src: "audio/ch0/beat7SimpleRule-014.wav",
        durationInFrames: 36,
      },
      {
        id: "beat7SimpleRule-015",
        text: "One. And that one rule handles every survival problem it will ever meet.",
        src: "audio/ch0/beat7SimpleRule-015.wav",
        durationInFrames: 134,
      },
      {
        id: "beat7SimpleRule-016",
        text: "One shape, quietly doing the work of many.",
        src: "audio/ch0/beat7SimpleRule-016.wav",
        durationInFrames: 92,
      },
      {
        id: "beat7SimpleRule-017",
        text: "That's the kind of thing we spend whole careers hunting for — the hidden pattern, the simple thing underneath the complicated thing.",
        src: "audio/ch0/beat7SimpleRule-017.wav",
        durationInFrames: 218,
      },
      {
        id: "beat7SimpleRule-018",
        text: "This cell has been showing it to us, in proteins, for three billion years.",
        src: "audio/ch0/beat7SimpleRule-018.wav",
        durationInFrames: 141,
      },
      {
        id: "beat7SimpleRule-019",
        text: "We just had to look.",
        src: "audio/ch0/beat7SimpleRule-019.wav",
        durationInFrames: 38,
      },
      {
        id: "beat7SimpleRule-020",
        text: "When the world gets better — keep going.",
        src: "audio/ch0/beat7SimpleRule-020.wav",
        durationInFrames: 72,
      },
      {
        id: "beat7SimpleRule-021",
        text: "When the world gets worse — change direction.",
        src: "audio/ch0/beat7SimpleRule-021.wav",
        durationInFrames: 82,
      },
      {
        id: "beat7SimpleRule-022",
        text: "Two lines. One tiny body, drifting through the dark, following them blindly, since long before anything on Earth could think a single thought.",
        src: "audio/ch0/beat7SimpleRule-022.wav",
        durationInFrames: 269,
      },
    ],
  },
  beat8Collide: {
    key: "beat8Collide",
    heading: "Beat 8 — When Food and Danger Collide",
    clips: [
      {
        id: "beat8Collide-000",
        text: "One more situation before we zoom out.",
        src: "audio/ch0/beat8Collide-000.wav",
        durationInFrames: 74,
      },
      {
        id: "beat8Collide-001",
        text: "And it's a tricky one.",
        src: "audio/ch0/beat8Collide-001.wav",
        durationInFrames: 40,
      },
      {
        id: "beat8Collide-002",
        text: "Most of the time, life is kind enough to hand the cell one thing at a time. Food today. Toxin tomorrow.",
        src: "audio/ch0/beat8Collide-002.wav",
        durationInFrames: 211,
      },
      {
        id: "beat8Collide-003",
        text: "Simple world, simple rule.",
        src: "audio/ch0/beat8Collide-003.wav",
        durationInFrames: 60,
      },
      {
        id: "beat8Collide-004",
        text: "But not always.",
        src: "audio/ch0/beat8Collide-004.wav",
        durationInFrames: 31,
      },
      {
        id: "beat8Collide-005",
        text: "Sometimes the food and the poison come from the same direction. The smell of sugar and the stink of something deadly, arriving together, from the same spot, at the same moment.",
        src: "audio/ch0/beat8Collide-005.wav",
        durationInFrames: 308,
      },
      {
        id: "beat8Collide-006",
        text: "So now what?",
        src: "audio/ch0/beat8Collide-006.wav",
        durationInFrames: 30,
      },
      {
        id: "beat8Collide-007",
        text: "You'd think it just freezes.",
        src: "audio/ch0/beat8Collide-007.wav",
        durationInFrames: 51,
      },
      {
        id: "beat8Collide-008",
        text: "The rule says keep going when things get better, change direction when they get worse — and right now it's both.",
        src: "audio/ch0/beat8Collide-008.wav",
        durationInFrames: 192,
      },
      {
        id: "beat8Collide-009",
        text: "Better and worse, same place.",
        src: "audio/ch0/beat8Collide-009.wav",
        durationInFrames: 62,
      },
      {
        id: "beat8Collide-010",
        text: "The rule seems to have no answer.",
        src: "audio/ch0/beat8Collide-010.wav",
        durationInFrames: 57,
      },
      {
        id: "beat8Collide-011",
        text: "You'd think that's it for our little blob.",
        src: "audio/ch0/beat8Collide-011.wav",
        durationInFrames: 64,
      },
      {
        id: "beat8Collide-012",
        text: "But watch.",
        src: "audio/ch0/beat8Collide-012.wav",
        durationInFrames: 22,
      },
      {
        id: "beat8Collide-013",
        text: "Inside the cell, two sensors fire at once.",
        src: "audio/ch0/beat8Collide-013.wav",
        durationInFrames: 94,
      },
      {
        id: "beat8Collide-014",
        text: "One shoves the molecular switch toward go. The other shoves it toward turn away. And the switch just… tips — toward whichever shove is stronger. Louder food signal? It goes. Toxin and all. Louder danger signal?",
        src: "audio/ch0/beat8Collide-014.wav",
        durationInFrames: 436,
      },
      {
        id: "beat8Collide-015",
        text: "It spins, turns, and leaves the meal behind.",
        src: "audio/ch0/beat8Collide-015.wav",
        durationInFrames: 101,
      },
      {
        id: "beat8Collide-016",
        text: "The cell doesn't freeze. It doesn't agonize.",
        src: "audio/ch0/beat8Collide-016.wav",
        durationInFrames: 88,
      },
      {
        id: "beat8Collide-017",
        text: "It just — somehow — settles it.",
        src: "audio/ch0/beat8Collide-017.wav",
        durationInFrames: 76,
      },
      {
        id: "beat8Collide-018",
        text: "Something is happening in there.",
        src: "audio/ch0/beat8Collide-018.wav",
        durationInFrames: 51,
      },
      {
        id: "beat8Collide-019",
        text: "Some quiet little contest between the signals, with a winner and a loser.",
        src: "audio/ch0/beat8Collide-019.wav",
        durationInFrames: 133,
      },
      {
        id: "beat8Collide-020",
        text: "The cell handles the conflict.",
        src: "audio/ch0/beat8Collide-020.wav",
        durationInFrames: 55,
      },
      {
        id: "beat8Collide-021",
        text: "It just has no idea that's what it's doing.",
        src: "audio/ch0/beat8Collide-021.wav",
        durationInFrames: 76,
      },
    ],
  },
  beatA1IfElse: {
    key: "beatA1IfElse",
    heading: "Algorithm Beat A1 — The If/Else",
    clips: [
      {
        id: "beatA1IfElse-000",
        text: "Okay, let's pause the story for a second — because I want to show you what we just watched from a completely different angle.",
        src: "audio/ch0/beatA1IfElse-000.wav",
        durationInFrames: 224,
      },
      {
        id: "beatA1IfElse-001",
        text: "The cell follows one rule.",
        src: "audio/ch0/beatA1IfElse-001.wav",
        durationInFrames: 48,
      },
      {
        id: "beatA1IfElse-002",
        text: "We saw it: when the world gets better, keep going; when it gets worse, change direction. Two lines.",
        src: "audio/ch0/beatA1IfElse-002.wav",
        durationInFrames: 208,
      },
      {
        id: "beatA1IfElse-003",
        text: "And those two lines handle everything — food, poison, all of it.",
        src: "audio/ch0/beatA1IfElse-003.wav",
        durationInFrames: 131,
      },
      {
        id: "beatA1IfElse-004",
        text: "Here's the part I love.",
        src: "audio/ch0/beatA1IfElse-004.wav",
        durationInFrames: 41,
      },
      {
        id: "beatA1IfElse-005",
        text: "If you've ever written even a single line of code — any language, doesn't matter — you've already written this exact shape.",
        src: "audio/ch0/beatA1IfElse-005.wav",
        durationInFrames: 222,
      },
      {
        id: "beatA1IfElse-006",
        text: "It even has a name.",
        src: "audio/ch0/beatA1IfElse-006.wav",
        durationInFrames: 36,
      },
      {
        id: "beatA1IfElse-007",
        text: "We call it if/else.",
        src: "audio/ch0/beatA1IfElse-007.wav",
        durationInFrames: 39,
      },
      {
        id: "beatA1IfElse-008",
        text: "If something is true, do one thing.",
        src: "audio/ch0/beatA1IfElse-008.wav",
        durationInFrames: 71,
      },
      {
        id: "beatA1IfElse-009",
        text: "Else, do the other.",
        src: "audio/ch0/beatA1IfElse-009.wav",
        durationInFrames: 46,
      },
      {
        id: "beatA1IfElse-010",
        text: "It's the simplest decision in all of computing.",
        src: "audio/ch0/beatA1IfElse-010.wav",
        durationInFrames: 80,
      },
      {
        id: "beatA1IfElse-011",
        text: "And notice what if/else never does: it never does both. The `if` branch runs, or the `else` branch runs.",
        src: "audio/ch0/beatA1IfElse-011.wav",
        durationInFrames: 198,
      },
      {
        id: "beatA1IfElse-012",
        text: "One, or the other.",
        src: "audio/ch0/beatA1IfElse-012.wav",
        durationInFrames: 41,
      },
      {
        id: "beatA1IfElse-013",
        text: "Never a little of each.",
        src: "audio/ch0/beatA1IfElse-013.wav",
        durationInFrames: 41,
      },
      {
        id: "beatA1IfElse-014",
        text: "Which is exactly what we just saw, right?",
        src: "audio/ch0/beatA1IfElse-014.wav",
        durationInFrames: 85,
      },
      {
        id: "beatA1IfElse-015",
        text: "The cell runs, or it tumbles — never both.",
        src: "audio/ch0/beatA1IfElse-015.wav",
        durationInFrames: 92,
      },
      {
        id: "beatA1IfElse-016",
        text: "Its threads bundle, or they fly apart — never both.",
        src: "audio/ch0/beatA1IfElse-016.wav",
        durationInFrames: 106,
      },
      {
        id: "beatA1IfElse-017",
        text: "And the part that gets me: nobody set it up that way to make the comparison work.",
        src: "audio/ch0/beatA1IfElse-017.wav",
        durationInFrames: 147,
      },
      {
        id: "beatA1IfElse-018",
        text: "The cell was already built like this, three billion years before anyone wrote the word 'else.",
        src: "audio/ch0/beatA1IfElse-018.wav",
        durationInFrames: 159,
      },
      {
        id: "beatA1IfElse-019",
        text: "That either-or lives in its body — the same either-or that lives in the code.",
        src: "audio/ch0/beatA1IfElse-019.wav",
        durationInFrames: 122,
      },
      {
        id: "beatA1IfElse-020",
        text: "So this isn't a metaphor we're draping over the cell to sound clever.",
        src: "audio/ch0/beatA1IfElse-020.wav",
        durationInFrames: 114,
      },
      {
        id: "beatA1IfElse-021",
        text: "It really is the shape the cell already is.",
        src: "audio/ch0/beatA1IfElse-021.wav",
        durationInFrames: 75,
      },
      {
        id: "beatA1IfElse-022",
        text: "Which means if/else isn't just the simplest decision in computing.",
        src: "audio/ch0/beatA1IfElse-022.wav",
        durationInFrames: 113,
      },
      {
        id: "beatA1IfElse-023",
        text: "It might be the first decision life ever made.",
        src: "audio/ch0/beatA1IfElse-023.wav",
        durationInFrames: 80,
      },
      {
        id: "beatA1IfElse-024",
        text: "Three billion years before there were programmers.",
        src: "audio/ch0/beatA1IfElse-024.wav",
        durationInFrames: 83,
      },
      {
        id: "beatA1IfElse-025",
        text: "Before there was language.",
        src: "audio/ch0/beatA1IfElse-025.wav",
        durationInFrames: 47,
      },
      {
        id: "beatA1IfElse-026",
        text: "Before there was anyone around to give it a name.",
        src: "audio/ch0/beatA1IfElse-026.wav",
        durationInFrames: 78,
      },
      {
        id: "beatA1IfElse-027",
        text: "Same shape, same job — deciding what happens next.",
        src: "audio/ch0/beatA1IfElse-027.wav",
        durationInFrames: 119,
      },
      {
        id: "beatA1IfElse-028",
        text: "In proteins, in silicon.",
        src: "audio/ch0/beatA1IfElse-028.wav",
        durationInFrames: 62,
      },
      {
        id: "beatA1IfElse-029",
        text: "The shape doesn't care.",
        src: "audio/ch0/beatA1IfElse-029.wav",
        durationInFrames: 38,
      },
    ],
  },
  beatA2WeightedSum: {
    key: "beatA2WeightedSum",
    heading: "Algorithm Beat A2 — The Implicit Weighted Sum",
    clips: [
      {
        id: "beatA2WeightedSum-000",
        text: "There's one more thing hiding in here — and it's the one that matters most for everything coming next.",
        src: "audio/ch0/beatA2WeightedSum-000.wav",
        durationInFrames: 166,
      },
      {
        id: "beatA2WeightedSum-001",
        text: "So stick with me.",
        src: "audio/ch0/beatA2WeightedSum-001.wav",
        durationInFrames: 37,
      },
      {
        id: "beatA2WeightedSum-002",
        text: "Go back to that moment the cell faced food and danger at the same time.",
        src: "audio/ch0/beatA2WeightedSum-002.wav",
        durationInFrames: 122,
      },
      {
        id: "beatA2WeightedSum-003",
        text: "Watch what was really going on underneath — in plain math.",
        src: "audio/ch0/beatA2WeightedSum-003.wav",
        durationInFrames: 105,
      },
      {
        id: "beatA2WeightedSum-004",
        text: "Each signal showed up with its own strength.",
        src: "audio/ch0/beatA2WeightedSum-004.wav",
        durationInFrames: 74,
      },
      {
        id: "beatA2WeightedSum-005",
        text: "Its own weight, baked right into the sensor that caught it.",
        src: "audio/ch0/beatA2WeightedSum-005.wav",
        durationInFrames: 99,
      },
      {
        id: "beatA2WeightedSum-006",
        text: "Those strengths got added together. Heavier side wins.",
        src: "audio/ch0/beatA2WeightedSum-006.wav",
        durationInFrames: 106,
      },
      {
        id: "beatA2WeightedSum-007",
        text: "Write that out, and you get:",
        src: "audio/ch0/beatA2WeightedSum-007.wav",
        durationInFrames: 52,
      },
      {
        id: "beatA2WeightedSum-008",
        text: "decision equals the sum of each signal, times its hidden weight.",
        src: "audio/ch0/beatA2WeightedSum-008.wav",
        durationInFrames: 119,
      },
      {
        id: "beatA2WeightedSum-009",
        text: "And there's one last piece.",
        src: "audio/ch0/beatA2WeightedSum-009.wav",
        durationInFrames: 48,
      },
      {
        id: "beatA2WeightedSum-010",
        text: "The cell's central switch — the thing every sensor pushes and pulls on — is never totally still.",
        src: "audio/ch0/beatA2WeightedSum-010.wav",
        durationInFrames: 177,
      },
      {
        id: "beatA2WeightedSum-011",
        text: "Even when nothing's arriving, no food, no poison, it keeps a low background hum. A default.",
        src: "audio/ch0/beatA2WeightedSum-011.wav",
        durationInFrames: 200,
      },
      {
        id: "beatA2WeightedSum-012",
        text: "A standing answer to the question, what do I do when nothing's happening?",
        src: "audio/ch0/beatA2WeightedSum-012.wav",
        durationInFrames: 132,
      },
      {
        id: "beatA2WeightedSum-013",
        text: "So the whole thing, written out, is:",
        src: "audio/ch0/beatA2WeightedSum-013.wav",
        durationInFrames: 79,
      },
      {
        id: "beatA2WeightedSum-014",
        text: "decision equals the sum of each signal times its hidden weight — plus a hidden baseline.",
        src: "audio/ch0/beatA2WeightedSum-014.wav",
        durationInFrames: 161,
      },
      {
        id: "beatA2WeightedSum-015",
        text: "That baseline has a name too.",
        src: "audio/ch0/beatA2WeightedSum-015.wav",
        durationInFrames: 55,
      },
      {
        id: "beatA2WeightedSum-016",
        text: "We call it a bias.",
        src: "audio/ch0/beatA2WeightedSum-016.wav",
        durationInFrames: 39,
      },
      {
        id: "beatA2WeightedSum-017",
        text: "Weighted sum, plus bias.",
        src: "audio/ch0/beatA2WeightedSum-017.wav",
        durationInFrames: 61,
      },
      {
        id: "beatA2WeightedSum-018",
        text: "That's about the simplest recipe there is for something that makes decisions.",
        src: "audio/ch0/beatA2WeightedSum-018.wav",
        durationInFrames: 125,
      },
      {
        id: "beatA2WeightedSum-019",
        text: "And this little bacterium has been running it, in pure chemistry, for three billion years.",
        src: "audio/ch0/beatA2WeightedSum-019.wav",
        durationInFrames: 163,
      },
      {
        id: "beatA2WeightedSum-020",
        text: "The math was real.",
        src: "audio/ch0/beatA2WeightedSum-020.wav",
        durationInFrames: 32,
      },
      {
        id: "beatA2WeightedSum-021",
        text: "Real numbers, hidden in molecules, quietly adding themselves up every second of every day — with nobody around who knew that's what they were.",
        src: "audio/ch0/beatA2WeightedSum-021.wav",
        durationInFrames: 262,
      },
      {
        id: "beatA2WeightedSum-022",
        text: "Though here's the catch — and it's worth holding onto, because the next chapter is built on it.",
        src: "audio/ch0/beatA2WeightedSum-022.wav",
        durationInFrames: 166,
      },
      {
        id: "beatA2WeightedSum-023",
        text: "In the cell, that sum was kind of an accident.",
        src: "audio/ch0/beatA2WeightedSum-023.wav",
        durationInFrames: 85,
      },
      {
        id: "beatA2WeightedSum-024",
        text: "A bunch of tiny switches all shoving the same molecule, and the total just… fell out of the physics.",
        src: "audio/ch0/beatA2WeightedSum-024.wav",
        durationInFrames: 194,
      },
      {
        id: "beatA2WeightedSum-025",
        text: "There was no spot anywhere in the cell whose actual job was to add things up.",
        src: "audio/ch0/beatA2WeightedSum-025.wav",
        durationInFrames: 130,
      },
      {
        id: "beatA2WeightedSum-026",
        text: "That's the math of the simple world.",
        src: "audio/ch0/beatA2WeightedSum-026.wav",
        durationInFrames: 56,
      },
    ],
  },
  beatC1NoOneDeciding: {
    key: "beatC1NoOneDeciding",
    heading: "Beat C1 — No One Is Deciding",
    clips: [
      {
        id: "beatC1NoOneDeciding-000",
        text: "And now the part that genuinely gets to me.",
        src: "audio/ch0/beatC1NoOneDeciding-000.wav",
        durationInFrames: 76,
      },
      {
        id: "beatC1NoOneDeciding-001",
        text: "The part that, if you actually sit with it, is a little hard to shake.",
        src: "audio/ch0/beatC1NoOneDeciding-001.wav",
        durationInFrames: 132,
      },
      {
        id: "beatC1NoOneDeciding-002",
        text: "Watch the cell from the outside, and it looks like it's hunting.",
        src: "audio/ch0/beatC1NoOneDeciding-002.wav",
        durationInFrames: 109,
      },
      {
        id: "beatC1NoOneDeciding-003",
        text: "It climbs toward the sugar, closing in, and honestly — it's hard not to think, the cell is looking for food. Watch it bolt away from a toxin and you'd swear it knows. It's scared.",
        src: "audio/ch0/beatC1NoOneDeciding-003.wav",
        durationInFrames: 343,
      },
      {
        id: "beatC1NoOneDeciding-004",
        text: "It's running for its life.",
        src: "audio/ch0/beatC1NoOneDeciding-004.wav",
        durationInFrames: 46,
      },
      {
        id: "beatC1NoOneDeciding-005",
        text: "But it doesn't know. Anything.",
        src: "audio/ch0/beatC1NoOneDeciding-005.wav",
        durationInFrames: 59,
      },
      {
        id: "beatC1NoOneDeciding-006",
        text: "Go in close — right down to the sensors, the proteins, the molecular switch — and look for whoever's making the call.",
        src: "audio/ch0/beatC1NoOneDeciding-006.wav",
        durationInFrames: 227,
      },
      {
        id: "beatC1NoOneDeciding-007",
        text: "There's nobody in there.",
        src: "audio/ch0/beatC1NoOneDeciding-007.wav",
        durationInFrames: 38,
      },
      {
        id: "beatC1NoOneDeciding-008",
        text: "No decider. No little self holding the scales.",
        src: "audio/ch0/beatC1NoOneDeciding-008.wav",
        durationInFrames: 100,
      },
      {
        id: "beatC1NoOneDeciding-009",
        text: "No part of the cell that knows it's choosing — because there's no part of the cell that knows anything at all.",
        src: "audio/ch0/beatC1NoOneDeciding-009.wav",
        durationInFrames: 179,
      },
      {
        id: "beatC1NoOneDeciding-010",
        text: "It isn't looking for food.",
        src: "audio/ch0/beatC1NoOneDeciding-010.wav",
        durationInFrames: 44,
      },
      {
        id: "beatC1NoOneDeciding-011",
        text: "It isn't fleeing the toxin.",
        src: "audio/ch0/beatC1NoOneDeciding-011.wav",
        durationInFrames: 48,
      },
      {
        id: "beatC1NoOneDeciding-012",
        text: "It's a chemical reaction.",
        src: "audio/ch0/beatC1NoOneDeciding-012.wav",
        durationInFrames: 47,
      },
      {
        id: "beatC1NoOneDeciding-013",
        text: "Sensors fire, propellers answer, the switch tips, the cell moves.",
        src: "audio/ch0/beatC1NoOneDeciding-013.wav",
        durationInFrames: 148,
      },
      {
        id: "beatC1NoOneDeciding-014",
        text: "And nobody's home to see it happen.",
        src: "audio/ch0/beatC1NoOneDeciding-014.wav",
        durationInFrames: 62,
      },
      {
        id: "beatC1NoOneDeciding-015",
        text: "And from the outside?",
        src: "audio/ch0/beatC1NoOneDeciding-015.wav",
        durationInFrames: 37,
      },
      {
        id: "beatC1NoOneDeciding-016",
        text: "It looks exactly like intelligence.",
        src: "audio/ch0/beatC1NoOneDeciding-016.wav",
        durationInFrames: 69,
      },
      {
        id: "beatC1NoOneDeciding-017",
        text: "That's the thing I keep coming back to: behavior that looks intelligent doesn't have to be intelligent.",
        src: "audio/ch0/beatC1NoOneDeciding-017.wav",
        durationInFrames: 178,
      },
      {
        id: "beatC1NoOneDeciding-018",
        text: "Something can spend three and a half billion years finding food, escaping danger, working out hard situations — looking, the whole time, like it means to — with no one inside who means anything by it.",
        src: "audio/ch0/beatC1NoOneDeciding-018.wav",
        durationInFrames: 391,
      },
      {
        id: "beatC1NoOneDeciding-019",
        text: "It's one of the strangest things in all of biology.",
        src: "audio/ch0/beatC1NoOneDeciding-019.wav",
        durationInFrames: 91,
      },
      {
        id: "beatC1NoOneDeciding-020",
        text: "And — I'll just say it now — it turns out to be one of the strangest things in AI, too.",
        src: "audio/ch0/beatC1NoOneDeciding-020.wav",
        durationInFrames: 182,
      },
      {
        id: "beatC1NoOneDeciding-021",
        text: "Even those hidden weights, the strengths of the signals — they were set the moment the cell was born.",
        src: "audio/ch0/beatC1NoOneDeciding-021.wav",
        durationInFrames: 169,
      },
      {
        id: "beatC1NoOneDeciding-022",
        text: "Same for every cell of its kind.",
        src: "audio/ch0/beatC1NoOneDeciding-022.wav",
        durationInFrames: 60,
      },
      {
        id: "beatC1NoOneDeciding-023",
        text: "Nobody chose them either.",
        src: "audio/ch0/beatC1NoOneDeciding-023.wav",
        durationInFrames: 45,
      },
      {
        id: "beatC1NoOneDeciding-024",
        text: "So the cell doesn't really make a decision.",
        src: "audio/ch0/beatC1NoOneDeciding-024.wav",
        durationInFrames: 75,
      },
      {
        id: "beatC1NoOneDeciding-025",
        text: "The cell is a decision — running on autopilot since the planet was warmer.",
        src: "audio/ch0/beatC1NoOneDeciding-025.wav",
        durationInFrames: 132,
      },
      {
        id: "beatC1NoOneDeciding-026",
        text: "And if you ask why this exact rule is still here, still running in the ocean today, the answer is almost embarrassingly simple: a very long time ago, the cells that did it this way lived.",
        src: "audio/ch0/beatC1NoOneDeciding-026.wav",
        durationInFrames: 344,
      },
      {
        id: "beatC1NoOneDeciding-027",
        text: "And the ones that did it any other way didn't.",
        src: "audio/ch0/beatC1NoOneDeciding-027.wav",
        durationInFrames: 67,
      },
    ],
  },
  beatC2TheLimit: {
    key: "beatC2TheLimit",
    heading: "Beat C2 — The Limit",
    clips: [
      {
        id: "beatC2TheLimit-000",
        text: "And it worked.",
        src: "audio/ch0/beatC2TheLimit-000.wav",
        durationInFrames: 25,
      },
      {
        id: "beatC2TheLimit-001",
        text: "For an almost unimaginable stretch of time, it just… worked.",
        src: "audio/ch0/beatC2TheLimit-001.wav",
        durationInFrames: 121,
      },
      {
        id: "beatC2TheLimit-002",
        text: "Three and a half billion years — basically the entire history of the planet — same simple rule, same kind of body. No brains. No nerves.",
        src: "audio/ch0/beatC2TheLimit-002.wav",
        durationInFrames: 283,
      },
      {
        id: "beatC2TheLimit-003",
        text: "No decisions, not in the way we usually mean the word. Just chemistry.",
        src: "audio/ch0/beatC2TheLimit-003.wav",
        durationInFrames: 140,
      },
      {
        id: "beatC2TheLimit-004",
        text: "And it was enough.",
        src: "audio/ch0/beatC2TheLimit-004.wav",
        durationInFrames: 32,
      },
      {
        id: "beatC2TheLimit-005",
        text: "A crude rule. Not elegant.",
        src: "audio/ch0/beatC2TheLimit-005.wav",
        durationInFrames: 57,
      },
      {
        id: "beatC2TheLimit-006",
        text: "Not even close to perfect.",
        src: "audio/ch0/beatC2TheLimit-006.wav",
        durationInFrames: 54,
      },
      {
        id: "beatC2TheLimit-007",
        text: "But it worked, for as long as there's been anything alive on Earth.",
        src: "audio/ch0/beatC2TheLimit-007.wav",
        durationInFrames: 108,
      },
      {
        id: "beatC2TheLimit-008",
        text: "And that's the good kind of good enough — the kind everything else gets to build on top of.",
        src: "audio/ch0/beatC2TheLimit-008.wav",
        durationInFrames: 150,
      },
      {
        id: "beatC2TheLimit-009",
        text: "A rough start. But a start.",
        src: "audio/ch0/beatC2TheLimit-009.wav",
        durationInFrames: 58,
      },
      {
        id: "beatC2TheLimit-010",
        text: "Still — there are things this little body just can't do.",
        src: "audio/ch0/beatC2TheLimit-010.wav",
        durationInFrames: 101,
      },
      {
        id: "beatC2TheLimit-011",
        text: "There's no place inside it whose only job is to weigh the options.",
        src: "audio/ch0/beatC2TheLimit-011.wav",
        durationInFrames: 113,
      },
      {
        id: "beatC2TheLimit-012",
        text: "The weights can't change while it's alive — they're locked in at birth.",
        src: "audio/ch0/beatC2TheLimit-012.wav",
        durationInFrames: 106,
      },
      {
        id: "beatC2TheLimit-013",
        text: "The bias can't be tuned.",
        src: "audio/ch0/beatC2TheLimit-013.wav",
        durationInFrames: 46,
      },
      {
        id: "beatC2TheLimit-014",
        text: "And nothing from inside the body ever gets a say.",
        src: "audio/ch0/beatC2TheLimit-014.wav",
        durationInFrames: 87,
      },
      {
        id: "beatC2TheLimit-015",
        text: "The math was there.",
        src: "audio/ch0/beatC2TheLimit-015.wav",
        durationInFrames: 31,
      },
      {
        id: "beatC2TheLimit-016",
        text: "The machinery to really use it wasn't.",
        src: "audio/ch0/beatC2TheLimit-016.wav",
        durationInFrames: 68,
      },
      {
        id: "beatC2TheLimit-017",
        text: "Not yet.",
        src: "audio/ch0/beatC2TheLimit-017.wav",
        durationInFrames: 23,
      },
    ],
  },
  beatC3WhatsAboutToArrive: {
    key: "beatC3WhatsAboutToArrive",
    heading: "Beat C3 — What's About to Arrive",
    clips: [
      {
        id: "beatC3WhatsAboutToArrive-000",
        text: "Which is exactly what's about to show up.",
        src: "audio/ch0/beatC3WhatsAboutToArrive-000.wav",
        durationInFrames: 73,
      },
      {
        id: "beatC3WhatsAboutToArrive-001",
        text: "The ocean is about to grow something bigger.",
        src: "audio/ch0/beatC3WhatsAboutToArrive-001.wav",
        durationInFrames: 70,
      },
      {
        id: "beatC3WhatsAboutToArrive-002",
        text: "A body with a front and a back — and somewhere in between, for the very first time, a place where signals can actually meet.",
        src: "audio/ch0/beatC3WhatsAboutToArrive-002.wav",
        durationInFrames: 237,
      },
      {
        id: "beatC3WhatsAboutToArrive-003",
        text: "A place that can weigh them on purpose.",
        src: "audio/ch0/beatC3WhatsAboutToArrive-003.wav",
        durationInFrames: 64,
      },
      {
        id: "beatC3WhatsAboutToArrive-004",
        text: "A place where the inside of the body finally gets a voice in what happens next.",
        src: "audio/ch0/beatC3WhatsAboutToArrive-004.wav",
        durationInFrames: 140,
      },
      {
        id: "beatC3WhatsAboutToArrive-005",
        text: "And once you've got a place like that — a place whose whole job is to weigh — something new becomes possible.",
        src: "audio/ch0/beatC3WhatsAboutToArrive-005.wav",
        durationInFrames: 191,
      },
      {
        id: "beatC3WhatsAboutToArrive-006",
        text: "Something we'll eventually learn to call intelligence.",
        src: "audio/ch0/beatC3WhatsAboutToArrive-006.wav",
        durationInFrames: 92,
      },
      {
        id: "beatC3WhatsAboutToArrive-007",
        text: "But that's next. For now: one simple world, running one simple rule. Complete.",
        src: "audio/ch0/beatC3WhatsAboutToArrive-007.wav",
        durationInFrames: 177,
      },
      {
        id: "beatC3WhatsAboutToArrive-008",
        text: "And something more, just about to begin.",
        src: "audio/ch0/beatC3WhatsAboutToArrive-008.wav",
        durationInFrames: 77,
      },
    ],
  },
} as const satisfies Record<string, BeatNarration>;

export type CH0BeatKey = keyof typeof narration;
